In [8]:
import os
from server_django.settings import BASE_DIR
# from utils.scoring import Scoring
from utils.mp_to_bvh_solution import BvhSolution, BvhNode
import numpy as np
from utils.video2mp_np import video2mp_np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.animation as animation
import mediapipe as mp
%matplotlib qt

In [3]:
config_dir = os.path.join(BASE_DIR, 'configs')
bvh1 = BvhSolution(
    os.path.join(config_dir, 'bvh_mp_config_final.json'),
    os.path.join(config_dir, 'mp_hierarchy.json'),
    os.path.join(config_dir, 'my5.bvh')
)

In [4]:

tmp1 = video2mp_np('./temp/videos/jumping_jacks1.mp4')
mp_data, frame_rate = tmp1['mp_data'], tmp1['frame_rate']

100%|██████████| 180/180 [00:06<00:00, 28.75it/s]


In [7]:
import utils.visualize_helper
utils.visualize_helper.anim_matchstickman(mp_data,30)

In [10]:
str(BASE_DIR)

'E:\\MyDocs\\repos\\sports_eva_service\\the_server'

In [13]:
bvh1.bvh_template_file

'E:\\MyDocs\\repos\\video2bvh_service_test\\server_test\\configs\\my5.bvh'

In [14]:
bvh1.nodes[1].offset

array([ 0., 20.,  0.])

In [5]:
bvh1.convert_mediapipe(mp_data)

converted bvh node:Hips, mediapipe node: 33, type:rigid

converted bvh node:Chest, mediapipe node: 35, type:rigid

converted bvh node:LeftShoulder, mediapipe node: 12, type:vector

converted bvh node:LeftElbow, mediapipe node: 14, type:vector

converted bvh node:LeftWrist, mediapipe node: 16, type:vector

converted bvh node:RightShoulder, mediapipe node: 11, type:vector

converted bvh node:RightElbow, mediapipe node: 13, type:vector

converted bvh node:RightWrist, mediapipe node: 15, type:vector

converted bvh node:Neck, mediapipe node: 34, type:rigid

converted bvh node:LeftHip, mediapipe node: 24, type:vector

converted bvh node:LeftKnee, mediapipe node: 26, type:vector

converted bvh node:LeftAnkle, mediapipe node: 28, type:vector

converted bvh node:RightHip, mediapipe node: 23, type:vector

converted bvh node:RightKnee, mediapipe node: 25, type:vector

converted bvh node:RightAnkle, mediapipe node: 27, type:vector



In [6]:
bvh1.write_bvh(frame_rate,'./jumping_jacks.bvh')

In [76]:
armature_one

array([[ -0.,  -0.,  -0.],
       [ -0., -20.,  -0.],
       [-20., -40.,  -0.],
       [-20., -15.,  -0.],
       [-20.,   7.,  -0.],
       [-20.,  22.,  -0.],
       [ 20., -40.,  -0.],
       [ 20., -15.,  -0.],
       [ 20.,   7.,  -0.],
       [ 20.,  22.,  -0.],
       [ -0., -40.,  -0.],
       [ -0., -55., -10.],
       [-10.,  -0.,  -0.],
       [-10.,  50.,  -0.],
       [-10.,  90.,  -0.],
       [-10.,  90., -20.],
       [ 10.,  -0.,  -0.],
       [ 10.,  50.,  -0.],
       [ 10.,  90.,  -0.],
       [ 10.,  90., -20.]])

In [6]:
import utils.visualize_helper
utils.visualize_helper.anim_bvh_armature(armature_np/100,30,bvh1)

NameError: name 'armature_np' is not defined

In [30]:
mp_data.shape[0]

172

In [36]:
armature_np[0,:,:]

array([[  0.,   0.,   0.],
       [  0.,  20.,   0.],
       [ 20.,  20.,   0.],
       [  0., -25.,   0.],
       [  0., -22.,   0.],
       [-20.,  20.,   0.],
       [  0., -25.,   0.],
       [  0., -22.,   0.],
       [  0.,  20.,   0.],
       [ 10.,   0.,   0.],
       [  0., -50.,   0.],
       [  0., -40.,   0.],
       [-10.,   0.,   0.],
       [  0., -50.,   0.],
       [  0., -40.,   0.]])

## update video2mp_np

In [2]:
import utils.video2mp_np
import importlib
importlib.reload(utils.video2mp_np)

# out=utils.video2mp_np.process_one_video('./temp/videos/high_knees1.mp4')
# out=utils.video2mp_np.process_one_video('./temp/videos/null.mp4')

out_np=utils.video2mp_np.video2mp_np('./temp/videos/inter3.mp4')

100%|██████████| 491/491 [00:15<00:00, 32.57it/s]


In [8]:
from utils.mp_visualize import anim_matchstickman
anim_raw_disp = anim_matchstickman(out_np['mp_data'], 30)

ModuleNotFoundError: No module named 'utils.mp_visualize'

In [34]:
out[1][0][1].pose_world_landmarks.landmark[0]

x: -0.014777712523937225
y: -0.6183986067771912
z: -0.3451542556285858
visibility: 0.9999967813491821

In [2]:
start=[utils.video2mp_np.PseudoLandmark(**{
    'x':0,
    'y':1,
    'z':2,
    'visibility':0.5,
}) for i in range(33)]
end=[utils.video2mp_np.PseudoLandmark(**{
    'x':1,
    'y':2,
    'z':3,
    'visibility':1,
}) for i in range(33)]
interped=utils.video2mp_np.PseudoLandmark.interpolate(start,end,33,4)

## test whole solution

In [ ]:
from utils.whole_solution import WholeSolution

s1=WholeSolution()


In [11]:
def func1(a,b,c,d):
    return a+b*c+d

func1(*(1,2,3,4))


11

In [17]:
def gene(count):
    for i in range(count):
        yield i

gene1=gene(3)

In [18]:
list(gene1)

[0, 1, 2]

In [19]:
parts={
    'holistic':None,
    'torso':None,
    'upper':None,
    'lower':None,
}

In [29]:
upper_index={3,4,5,7,8,9}
lower_index=remain-upper_index
parts['upper']=list(upper_index)
parts['lower']=list(lower_index)

In [28]:
remain

{3, 4, 5, 7, 8, 9, 13, 14, 15, 17, 18, 19}

In [30]:
parts

{'holistic': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19],
 'torso': [0, 1, 2, 6, 10, 11, 12, 16],
 'upper': [3, 4, 5, 7, 8, 9],
 'lower': [13, 14, 15, 17, 18, 19]}

In [41]:
import json
with open('./configs/scoring_parts.json','w') as f:
    f.write(json.dumps(parts,indent=4))

In [40]:
json.dumps?

In [52]:
# type(plt.figure())
tmp=plt.figure()
tmp1=tmp.add_subplot(projection='3d')

In [53]:
type(tmp1)

matplotlib.axes._subplots.Axes3DSubplot

In [10]:
import utils.visualize_helper
import importlib
importlib.reload(utils.visualize_helper)

# utils.visualize_helper.anim_matchstickman(mp_data,30)


utils.visualize_helper.anim_bvh_armature(armature_np/100,30,bvh1)

NameError: name 'armature_np' is not defined

In [73]:
mp_data[0]

array([[-1.47777125e-02, -6.18398607e-01, -3.45154256e-01,
         9.99996781e-01],
       [-4.17870842e-03, -6.56241119e-01, -3.30605298e-01,
         9.99987364e-01],
       [-3.72469332e-03, -6.56636715e-01, -3.29943478e-01,
         9.99986172e-01],
       [-3.70719004e-03, -6.56992853e-01, -3.30005318e-01,
         9.99986410e-01],
       [-3.68003808e-02, -6.52626693e-01, -3.30212384e-01,
         9.99989510e-01],
       [-3.64499427e-02, -6.53570056e-01, -3.31062943e-01,
         9.99989271e-01],
       [-3.65386531e-02, -6.54824317e-01, -3.30054462e-01,
         9.99989748e-01],
       [ 4.74725440e-02, -6.44234419e-01, -2.21848235e-01,
         9.99974847e-01],
       [-9.97942910e-02, -6.39731288e-01, -2.30146825e-01,
         9.99977589e-01],
       [ 7.16000143e-03, -5.93687892e-01, -3.06380361e-01,
         9.99995708e-01],
       [-3.55545655e-02, -5.90517104e-01, -3.07595402e-01,
         9.99996066e-01],
       [ 1.49611264e-01, -4.53254014e-01, -1.36338979e-01,
      

In [75]:
anim_matchstickman(mp_data[0:2],30)

In [3]:
bvh1.get_all_mp_children(24)

[26, 28, 30, 32]

[4, 5]

In [88]:
importlib.reload(utils.mp_to_bvh_solution)

<module 'utils.mp_to_bvh_solution' from 'E:\\MyDocs\\repos\\video2bvh_service_test\\server_test\\utils\\mp_to_bvh_solution.py'>

In [39]:
import utils.whole_solution
import importlib
import utils.visualize_helper
importlib.reload(utils.whole_solution)
arma1=utils.whole_solution.Scoring.armature_from_bvh(bvh1)
utils.whole_solution.Scoring.rotate_armature_by_bvh(arma1,bvh1)

In [30]:
utils.visualize_helper.anim_bvh_armature(arma1/100,30,bvh1)

In [38]:
scoring1=utils.whole_solution.Scoring(bvh1,'./configs/scoring_parts_bvh.json')
scoring1.scoring_parts['holistic']

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [12]:
bvh1.nodes[0].dcm[0,:,:]
np.linalg.inv

array([[ 0.99998493,  0.00399642,  0.00376348],
       [-0.00494788,  0.9531087 ,  0.30258773],
       [-0.00237774, -0.30260179,  0.95311411]])

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
 

In [6]:
config_dir = os.path.join(BASE_DIR, 'configs')
bvh2 = BvhSolution(
    os.path.join(config_dir, 'bvh_mp_config_tpose.json'),
    os.path.join(config_dir, 'mp_hierarchy.json'),
    os.path.join(config_dir, 'my6_tpose.bvh')
)

In [3]:
tmp2 = video2mp_np('./temp/videos/high_knees1.mp4')
mp_data, frame_rate = tmp2['mp_data'], tmp2['frame_rate']

100%|██████████| 177/177 [00:07<00:00, 24.50it/s]


In [7]:
bvh2.convert_mediapipe(mp_data)

converted bvh node:Hips, mediapipe node: 33, type:rigid

converted bvh node:Chest, mediapipe node: 35, type:rigid

converted bvh node:LeftShoulder, mediapipe node: 12, type:vector

converted bvh node:LeftElbow, mediapipe node: 14, type:vector

converted bvh node:LeftWrist, mediapipe node: 16, type:vector

converted bvh node:RightShoulder, mediapipe node: 11, type:vector

converted bvh node:RightElbow, mediapipe node: 13, type:vector

converted bvh node:RightWrist, mediapipe node: 15, type:vector

converted bvh node:Neck, mediapipe node: 34, type:rigid

converted bvh node:LeftHip, mediapipe node: 24, type:vector

converted bvh node:LeftKnee, mediapipe node: 26, type:vector

converted bvh node:LeftAnkle, mediapipe node: 28, type:vector

converted bvh node:RightHip, mediapipe node: 23, type:vector

converted bvh node:RightKnee, mediapipe node: 25, type:vector

converted bvh node:RightAnkle, mediapipe node: 27, type:vector



In [12]:
utils.visualize_helper.anim_matchstickman(bvh2.mp_data,30)

In [13]:
bvh2.write_bvh(30,'./tpose_out.bvh')